### PR TITLE
WIP: New implementation

### PR DESCRIPTION
**Pull request by fast4d**

### CODE REVIEW

**Comment by eachali** [comment]
@ecleel changes done

**Comment by fast4d** [comment]
@ecleel Added [Change Log](https://github.com/moyasar/moyasar-php/pull/15/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)

**Comment by ecleel** [comment]
@fast4d Great work. Shall we do the merge?

**Comment by fast4d** [comment]
Yes, please. When you tag the new release please make sure it has the label `1.0.0`

The good thing about Composer is that it uses this constraint `^0.5.0` by default when a user does:

```bash
composer require moyasar/moyasar
```

This will make sure whenever they update their packages, their version of our library will be `>=0.5.0 && <1.0.0`

**Pull request merged**
